import React, { useState } from 'react'
import {
  Zap,
  X,
  Copy,
  Check,
  Download,
  Share2,
  Sparkles,
  FileCheck2,
  ExternalLink,
} from 'lucide-react'
import { HighlightItem, Project } from '../types'
import { safeCopyText } from '../utils/clipboard'

interface SynthesisModalProps {
  isOpen: boolean
  onClose: () => void
  currentProject: Project
  highlights: HighlightItem[]
}

export const SynthesisModal: React.FC<SynthesisModalProps> = ({
  isOpen,
  onClose,
  currentProject,
  highlights,
}) => {
  const [copied, setCopied] = useState(false)
  const [exportedFormat, setExportedFormat] = useState<string | null>(null)

  if (!isOpen) return null

  // Generate full Markdown synthesis report based on project highlights
  const generateMarkdownReport = () => {
    const keypoints = highlights.filter((h) => h.type === 'amber')
    const codeSops = highlights.filter((h) => h.type === 'emerald')
    const todos = highlights.filter((h) => h.type === 'coral')

    return `# AI 核心精简总结报告 (Synthesis Report)
**项目**: ${currentProject.name}
**生成时间**: ${new Date().toLocaleString()}
**收集精金句数**: ${highlights.length} 条

---

## 核心划重点与战略结论 (Key Takeaways)
${
  keypoints.length > 0
    ? keypoints.map((k, i) => `${i + 1}. ${k.text} *(来自 #${k.nodeId})*`).join('\n')
    : '_暂无重点记录_'
}

---

## 核心代码 & SOP 落地指南 (Code & SOP)
${
  codeSops.length > 0
    ? codeSops.map((c, i) => `${i + 1}. ${c.text} *(来自 #${c.nodeId})*`).join('\n')
    : '_暂无代码记录_'
}

---

## 疑问 & 待办清单 (Todos & Follow-ups)
${
  todos.length > 0
    ? todos.map((t, i) => `- [ ] ${t.text} *(来自 #${t.nodeId})*`).join('\n')
    : '_暂无待办事项_'
}

---
*Generated by LiquidFlow AI Synthesis Engine*`
  }

  const reportMarkdown = generateMarkdownReport()

  const handleCopyReport = async () => {
    await safeCopyText(reportMarkdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExportFile = (format: 'markdown' | 'obsidian' | 'txt') => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${currentProject.name}-Synthesis-Report.${format === 'txt' ? 'txt' : 'md'}`
    a.click()
    URL.revokeObjectURL(url)
    setExportedFormat(format)
    setTimeout(() => setExportedFormat(null), 2000)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="w-full max-w-2xl bg-[#161618] rounded-xl border border-white/12 shadow-xl shadow-black/40 overflow-hidden flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="p-4 border-b border-white/8 flex items-center justify-between bg-[#111113]">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-md bg-[#cba86a] text-black">
              <Zap className="w-5 h-5 fill-black" />
            </div>
            <div>
              <h2 className="font-bold text-gray-100 text-base">
                一键 AI 结构化总结报告 (Synthesis Report)
              </h2>
              <p className="text-xs text-gray-400">已智能提炼 {highlights.length} 条核心脉络卡片</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-md text-gray-400 hover:text-gray-100 hover:bg-white/[0.08] transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Report Preview */}
        <div className="flex-1 p-4 overflow-y-auto font-mono text-xs text-gray-300 bg-[#0f0f11] border-b border-white/8 leading-relaxed whitespace-pre-wrap select-text">
          {reportMarkdown}
        </div>

        {/* Export Action Buttons */}
        <div className="p-4 bg-[#111113] flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-2">
            <button
              onClick={() => handleExportFile('markdown')}
              className="px-3 py-2 rounded-md bg-white/[0.04] hover:bg-white/[0.08] text-gray-200 hover:text-gray-100 border border-white/8 text-xs font-medium transition flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>导出为 .md</span>
            </button>

            <button
              onClick={() => handleExportFile('obsidian')}
              className="px-3 py-2 rounded-md bg-white/[0.04] hover:bg-white/[0.08] text-gray-200 hover:text-gray-100 border border-white/8 text-xs font-medium transition flex items-center gap-1.5"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span>同步至 Obsidian</span>
            </button>
          </div>

          <button
            onClick={handleCopyReport}
            className="px-4 py-2 rounded-md bg-[#cba86a] hover:bg-[#d8b877] text-black font-bold text-xs transition flex items-center gap-1.5"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-black" />
                <span>已成功复制全部报告!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 text-black" />
                <span>复制精简报告全文</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  )
}
